image: Visual Studio 2022

environment:
  matrix:
    - compiler: mingw
    - compiler: vs

install:
  - if "%compiler%" == "mingw" choco install mingw --no-progress
  - if "%compiler%" == "mingw" set PATH=C:\\ProgramData\\chocolatey\\bin;%PATH%

build_script:
  - if "%compiler%" == "mingw" (
        mkdir _build && cd _build &&
        cmake -G "MinGW Makefiles" .. &&
        cmake --build .
      )
  - if "%compiler%" == "vs" (
        mkdir _build && cd _build &&
        cmake -G "Visual Studio 17 2022" .. &&
        cmake --build .
      )

test_script:
  - cd _build
  - ctest --output-on-failure
